### ISSUE TITLE
strict grid doesn't allow closing polygons

### ISSUE THREAD

**Issue by bgschiller** [NatLabRockies/floorspace.js#158]

**Comment by bgschiller** [comment]
(This is now fixed on develop)

**Comment by shorowit** [comment]
This still fails for some situations. I think it depends on whether the start/end point is on top of an existing polygon vertex or not. Examples below.

Works:
[Aug 22 2017 4-23 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1243562/Aug.22.2017.4-23.PM.webm.txt)

Fails:
[Aug 22 2017 4-24 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1243566/Aug.22.2017.4-24.PM.webm.txt)
